########## 配置数据源 （Druid）##########
spring:
  datasource:
    ########## JDBC 基本配置 ##########
    username: zack
    password: tangyong
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql8 的连接驱动
    url: jdbc:mysql://1241.70.71.131:3306/zack?serverTimezone=UTC&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource  # 指定数据源类型
